### ISSUE TITLE
wrong version of skopeo in CAHC

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#156]
In the latest CAHC build (Version: 7.2016.220 (2016-09-22 14:00:42)), the version of `skopeo` isn't what I expected to see after #155 was merged.

```
# rpm -q skopeo
skopeo-0.1.13-8.el7.x86_64
```

The build artifacts shows that the "right" version was built, but I don't know why it wasn't included in the compose.

https://ci.centos.org/artifacts/sig-atomic/rdgo/centos-continuous/build/

Maybe `atomic` is dragging in a different version?

**Comment by miabbott** [comment]
Or maybe I broke it when I changed this:

https://github.com/CentOS/sig-atomic-buildscripts/blob/master/overlay.yml#L84

**Comment by cgwalters** [comment]
See https://github.com/CentOS/sig-atomic-buildscripts/pull/157

The problem is that the version in C7Extras has an epoch.

**Comment by miabbott** [comment]
Thanks @cgwalters!

**Comment by miabbott** [comment]
Looks like skopeo is also being provided by `virt7-docker-el-candidate`

```
17:00:43   skopeo-1:0.1.13-6.el7.x86_64 (virt7-docker-el-candidate)
```

**Comment by miabbott** [comment]
Submitted #158 to try to fix it again

**Comment by miabbott** [comment]
:raised_hands: 

```
# rpm-ostree status
State: idle
Deployments:
● centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
       Version: 7.2016.227 (2016-09-22 20:00:54)
        Commit: ff861b5bb9ad9d95187db59c2a9722f7e39cf369a1591e74465fb0e0b1d0dfe0
        OSName: centos-atomic-host

# rpm -qa atomic skopeo
atomic-1.12.4.2-488c096b77a0aa22ea0ee68d4d5d08cd607f7f95.017527d1613c2e9e6efa24a5140b35a2ea89a494.el7.centos.x86_64
skopeo-1.14-d8303916d52272e08d92163bba18e30c50ee24d7.0aa48eb05ef9b646ac444ddc878eb93dbd3d6d98.el7.centos.x86_64
```
