### ISSUE TITLE
downstream CentOS Atomic Host + CAHC missing 'atomic-registries' package

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#316]
The new way of configuring registries (insecure or defaults) is via `/etc/containers/registries.conf` file which is provided via the `atomic-registries` package.  This is usually built as part of the `atomic` package, see the spec file here:

http://pkgs.fedoraproject.org/cgit/rpms/atomic.git/tree/atomic.spec#n114

In RHEL Atomic Host, we can see the `atomic-registries` package is included:

```
# rpm-ostree status    
State: idle
Deployments:
● rhel-atomic-host-ostree:rhel-atomic-host/7/x86_64/standard
                   Version: 7.4.3-1 (2018-01-04 17:38:17)
                    Commit: 83350a7fb3a3ebd09c5996eec5ec8307f61bbb463b999bdfece223288927a60f
              GPGSignature: Valid signature by 567E347AD0044ADE55BA8A5F199E2F91FD431D51
# rpm -q atomic atomic-registries
atomic-1.20.1-3.git840732d.el7.x86_64
atomic-registries-1.20.1-3.git840732d.el7.x86_64
```

But it is missing from downstream CentOS Atomic Host:

```
$ rpm-ostree status
State: idle
Deployments:
● centos-atomic-host:centos-atomic-host/7/x86_64/standard
                   Version: 7.1712.1 (2018-01-12 10:25:04)
                    Commit: c6104b6bd8aeabbc19687e91359657e1292c3669e3c686438993e48481af6f2d
              GPGSignature: Valid signature by 64E3E7558572B59A319452AAF17E745691BA8335
$ rpm -q atomic atomic-registries
atomic-1.20.1-9.git436cf5d.el7.centos.x86_64
package atomic-registries is not installed
```

And missing from CAHC

```
# rpm-ostree status
State: idle
Deployments:
● ostree://centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
                   Version: 7.2017.996 (2018-01-17 19:06:38)
                    Commit: 3a463dc6b5dfa9da062cf9d145a7113778f312a78ecfd764aa20af80a160f78e
# rpm -q atomic atomic-registries
atomic-1.20.1-9.git436cf5d.el7.centos.x86_64
package atomic-registries is not installed
```

I don't know why the CentOS rebuild would exclude this package, but I'm hoping someone else understands what has happened.
