### ISSUE TITLE
`firewalld` enabled by default on CAHC; doesn't match CentOS AH

### ISSUE THREAD

**Issue by miabbott** [CentOS/sig-atomic-buildscripts#342]
Unexpectedly, when we rebase from the `centos/7/atomic/smoketested` image to the latest CAHC commit, the `firewalld` service is enabled:

```
# rpm-ostree status
State: idle; auto updates disabled
Deployments:
● ostree://custom:centos-atomic-host/7/x86_64/devel/continuous
                   Version: 7.2018.86 (2018-06-29 22:22:59)
                    Commit: 2fb973548aa973acb12cfb64ff12bffd98c4b3ad1816fcf6b0aef76b651804b0


ostree://centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/smoketested
                   Version: 7.2017.1173 (2018-05-14 20:42:32)
                    Commit: 04ac687ab8d904f72edf2077ba47d7de0edea1c2116f83e38f6cfe92d7fd90f4

# systemctl is-enabled firewalld
enabled

# rpm -q firewalld
firewalld-0.4.4.4-14.el7.noarch
```

This is bizarre since the CentOS AH image/commit has the service disabled by default and they share the same RPM:

```
# rpm-ostree status
State: idle
Deployments:
● ostree://centos-atomic-host:centos-atomic-host/7/x86_64/standard
                   Version: 7.1805 (2018-06-11 11:03:09)
                    Commit: 6275caab694c56515c57f5e5ef923d999e16e8fb1241992d155ff03cfb528261
              GPGSignature: Valid signature by 64E3E7558572B59A319452AAF17E745691BA8335

# systemctl is-enabled firewalld
disabled

# rpm -q firewalld
firewalld-0.4.4.4-14.el7.noarch 
```
